apiVersion: v1
kind: Service
metadata:
  name: auction-engine-cs
  labels:
    app: auction-engine-pd
spec:
  ports:
  - port: 8180
    targetPort: 8383
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: auction-engine-pd
