apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: infinispan-pd
  labels:
    app: infinispan-pd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: infinispan-pd
    spec:
      containers:
        - name: infinispan-pd
          image: jboss/infinispan-server:9.2.3.Final
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2G"
              cpu: "500m"
            limits:
              memory: "4G"
              cpu: "1000m"
          args:
            - cloud
            - -Djboss.default.jgroups.stack=kubernetes
          env:
          - name: KUBERNETES_NAMESPACE
            value: [KUBERNETES_NAMESPACE]
          - name: MGMT_USER
            value: [ADMIN_USER]
          - name: MGMT_PASS
            value: [PASSWORD]
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8181
            protocol: TCP
          - containerPort: 8888
            protocol: TCP
          - containerPort: 9990
            protocol: TCP
          - containerPort: 11211
            protocol: TCP
          - containerPort: 11222
            protocol: TCP
