apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: [KUBERNETES_NAMESPACE]
subjects:
- kind: ServiceAccount
  name: default
  namespace: [KUBERNETES_NAMESPACE]
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
