apiVersion: v1
kind: Service
metadata:
  name: core-api-cs
  labels:
    app: core-api-cs
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: core-api-pd
