apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: config-app-pd
  name: config-app-pd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: config-app-pd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: config-app-pd
        run: config-app-pd
    spec:
      containers:
        - image: gcr.io/sincere-blade-199211/tdaux/config-app-microservice:1.0.0
          imagePullPolicy: Always
          name: config-app-pd
          resources:
            requests:
              memory: "500M"
              cpu: "500m"
            limits:
              memory: "1G"
              cpu: "1000m"
          ports:
          - containerPort: 10073
            protocol: TCP
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=sincere-blade-199211:asia-south1:tdaux-dev-instance=tcp:0.0.0.0:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END volumes]
