apiVersion: v1
kind: Service
metadata:
  name: config-app-cs
  labels:
    name: config-app-cs
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: cluster
      port: 10073
      targetPort: 10073
  selector:
    app: config-app-pd
