apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-app-pd
  labels:
    app: config-app-pd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-app-pd
    spec:
      containers:
        - name: config-app-pd
          image: gcr.io/[PROJECT_NAME]/tdaux/config-app-microservice:1.0.0
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: DATABASE_NAME
              value: [DB_NAME]
            - name: DB_USER
              value: [USER]
            - name: DB_PASSWORD
              value: [PASSWORD]
          resources:
            requests:
              memory: "500M"
              cpu: "500m"
            limits:
              memory: "1G"
              cpu: "1000m"
          ports:
          - containerPort: 10073
            protocol: TCP
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=[INSTANCE_CONNECTION_NAME]=tcp:0.0.0.0:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END volumes]
