apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openfire
  labels:
    app: openfire
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openfire
    spec:
      containers:
        - name: openfire
          image: gcr.io/sincere-blade-199211/jboss/openfire-cloud
          resources:
            requests:
              memory: "1G"
              cpu: "1G"
            limits:
              memory: "2G"
              cpu: "1000m"
          env:
          - name: "DNS_DOMAIN"
            value: "cluster.local"
          - name: "HAZELCAST_KUBERNETES_SERVICE_DNS"
            value: "openfire.default.svc.cluster.local"
          ports:
          - containerPort: 9090
            protocol: TCP
          - containerPort: 5222
            protocol: TCP
          - containerPort: 7070
            protocol: TCP
          - containerPort: 5005
            protocol: TCP
          - containerPort: 5701
            protocol: TCP
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=sincere-blade-199211:asia-south1:tdaux-dev-instance=tcp:0.0.0.0:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END volumes]
