apiVersion: v1
kind: Service
metadata:
  labels:
    name: openfire-cs
  name: openfire-cs
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 5701
      targetPort: 5701
  selector:
    app: openfire
