apiVersion: v1
kind: Service
metadata:
  labels:
    name: openfire
  name: openfire
spec:
  clusterIP: None
  type: ClusterIP   
  ports:
    - port: 5701
      targetPort: 5701
  selector:
    app: openfire
