apiVersion: v1
kind: Service
metadata:
  name: openfire-cs
  labels:
    name: openfire-cs
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: cluster
      port: 5701
      targetPort: 5701
    - name: client
      port: 5222
      targetPort: 5222
    - name: http
      port: 7070
      targetPort: 7070
  selector:
    app: openfire-pd
