apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openfire-pd
  labels:
    app: openfire-pd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openfire-pd
    spec:
      containers:
        - name: openfire-pd
          image: gcr.io/[PROJECT_NAME]/tdaux/openfire:4.0.3.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1G"
              cpu: "500m"
            limits:
              memory: "2G"
              cpu: "1000m"
          env:
          - name: "DNS_DOMAIN"
            value: "cluster.local"
          - name: "HAZELCAST_KUBERNETES_SERVICE_DNS"
            value: "openfire-cs.default.svc.cluster.local"
          ports:
          - containerPort: 9090
            protocol: TCP
          - containerPort: 5222
            protocol: TCP
          - containerPort: 7070
            protocol: TCP
          - containerPort: 5005
            protocol: TCP
          - containerPort: 5701
            protocol: TCP
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=[INSTANCE_CONNECTION_NAME]=tcp:0.0.0.0:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END volumes]
