apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: flume-agent-delete-index-pd
  name: flume-agent-delete-index-pd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flume-agent-delete-index-pd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flume-agent-delete-index-pd
        run: flume-agent-delete-index-pd
    spec:
      containers:
        - image: gcr.io/[PROJECT_NAME]/tdaux/flume-agent-delete-index:1.0.0
          imagePullPolicy: Always
          name: flume-agent-delete-index-pd
          resources:
            requests:
              memory: "1G"
              cpu: "500m"
            limits:
              memory: "2G"
              cpu: "1000m"
          env :
          - name: "CONF_FILE"
            value: "/etc/conf/delete-index.conf"
          - name: "AGENT_NAME"
            value: "flume-delete-index-agent"
          volumeMounts:
            - name: "config-volume"
              mountPath: "/etc/conf/delete-index.conf"
              subPath: "delete-index.conf"
      volumes:
        - name: "config-volume"
        configMap:
          name: "flume-config"
