apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: tdaux-web-pd
  name: tdaux-web-pd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tdaux-web-pd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tdaux-web-pd
        run: tdaux-web-pd
    spec:
      containers:
        - image: gcr.io/[PROJECT_NAME]/tdaux/tdaux-web:1.0.0
          command:
          - "/opt/jboss/wildfly/bin/standalone.sh"
          args:
          - "--server-config"
          - "standalone-full.xml"
          - "-b"
          - "0.0.0.0"
          - "-bmanagement"
          - "0.0.0.0"
          env:
          - name: "TDAUX_APP_CONF"
            value: "config-app-cs.default.svc.cluster.local:10073"
          - name: "CONF_CODE"
            value: "E4AA38261FE04C4C9EB4B8A1465CDFA6"
          imagePullPolicy: Always
          name: tdaux-web-pd
          resources:
            requests:
              memory: "1G"
              cpu: "500m"
            limits:
              memory: "2G"
              cpu: "1000m"
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 9990
            protocol: TCP
