apiVersion: v1
kind: Service
metadata:
  name: wildfly-cs
  labels:
    app: wildfly-pd
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: wildfly-pd
