apiVersion: v1
kind: Service
metadata:
  name: kafka-cs
  labels:
    app: kafka-cs
spec:
  ports:
  - port: 10073
    targetPort: 10073
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: kafka-pd
